spring:
  application:
    name: notification-service

#  Zipkin e Sleuth
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
    integration:
      enabled: true

  # Kafka properties
  kafka:
    bootstrap:
      bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.emendes.notificationservice.event.OrderPlacedEvent
      group-id: notificationId

# eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

server:
  port: 8085