eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

spring:
  application:
    name: api-gateway

  ## Product service route
  cloud:
    gateway:
      routes:
      - id: product-service
        uri: lb://product-service
        predicates:
        - Path=/api/products

  ## Order service route
      - id: order-service
        uri: lb://order-service
        predicates:
        - Path=/api/orders

  ## Discovery server route
      - id: discovery-server
        uri: http://localhost:8761
        predicates:
        - Path=/eureka/web
        filters:
        - SetPath=/

  ## Discovery server static resources route
      - id: discovery-server-static
        uri: http://localhost:8761
        predicates:
        - Path=/eureka/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-boot-microservices-realm

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
#            route:
#              RouteDefinitionRouteLocator: INFO


