# datasource
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service-db
#      uri: mongodb://root:example@localhost:27017/product-service-db
#      host: localhost
#      port: 27017
#      database: product-service-db
#      username: root
#      password: example

  application:
    name: product-service

  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1

# eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

server:
  port: 8083

# Actuator Prometheus endpoint
management:
  endpoints:
    web:
      exposure:
        include: prometheus
