# datasource
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service-db
#      uri: mongodb://root:example@localhost:27017/product-service-db
#      host: localhost
#      port: 27017
#      database: product-service-db
#      username: root
#      password: example

  application:
    name: product-service

# eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8083
