# datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory-db?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: inventory-service

# jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true

  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1

# log
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type: trace

# eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

# port
server:
  port: 8088